openapi: 3.1.0
info:
  title: Theme Variables Contract
  version: 1.0.0
  description: CSS custom properties contract for blue theme configuration

components:
  schemas:
    ThemeVariables:
      type: object
      required:
        - colors
        - radius
      properties:
        colors:
          type: object
          required:
            - background
            - foreground
            - primary
            - primary-foreground
            - secondary
            - secondary-foreground
            - accent
            - accent-foreground
            - muted
            - muted-foreground
            - destructive
            - destructive-foreground
            - border
            - input
            - ring
            - card
            - card-foreground
            - popover
            - popover-foreground
          properties:
            background:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(1 0 0)'
            foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.145 0 0)'
            primary:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.47 0.17 255)'
              description: Blue primary color for CTAs and brand elements
            primary-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.985 0 0)'
            secondary:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.97 0 0)'
            secondary-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.205 0 0)'
            accent:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.52 0.15 255)'
              description: Accent blue for highlights
            accent-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.985 0 0)'
            muted:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.97 0 0)'
            muted-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.556 0 0)'
            destructive:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.577 0.245 27.325)'
            destructive-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.985 0 0)'
            border:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.922 0 0)'
            input:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.922 0 0)'
            ring:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.47 0.17 255)'
              description: Focus ring color (matches primary)
            card:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(1 0 0)'
            card-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.145 0 0)'
            popover:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(1 0 0)'
            popover-foreground:
              type: string
              pattern: '^oklch\([0-9.]+ [0-9.]+ [0-9.]+\)$'
              example: 'oklch(0.145 0 0)'

        radius:
          type: object
          required:
            - base
            - sm
            - md
            - lg
            - xl
          properties:
            base:
              type: string
              pattern: '^[0-9.]+rem$'
              example: '0.5rem'
            sm:
              type: string
              example: 'calc(var(--radius) - 4px)'
            md:
              type: string
              example: 'calc(var(--radius) - 2px)'
            lg:
              type: string
              example: 'var(--radius)'
            xl:
              type: string
              example: 'calc(var(--radius) + 4px)'

    DarkModeOverrides:
      type: object
      description: Dark mode specific color overrides
      properties:
        background:
          type: string
          example: 'oklch(0.145 0 0)'
        foreground:
          type: string
          example: 'oklch(0.985 0 0)'
        primary:
          type: string
          example: 'oklch(0.52 0.15 255)'
          description: Slightly lighter blue for dark mode
        # ... other overrides

paths: {}
