apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: credit-card-processor
spec:
  provider: azure
  parameters:
    # Use workload identity for authentication (no service principal needed)
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ""  # Workload identity client ID set via serviceAccountName

    # Azure Key Vault details (replace with actual Key Vault name)
    keyvaultName: "${AZURE_KEYVAULT_NAME}"
    cloudName: AzurePublicCloud
    tenantId: "${AZURE_TENANT_ID}"

    # Secrets to retrieve from Key Vault
    objects: |
      array:
        - |
          objectName: postgres-db
          objectType: secret
          objectAlias: POSTGRES_DB
        - |
          objectName: postgres-user
          objectType: secret
          objectAlias: POSTGRES_USER
        - |
          objectName: postgres-password
          objectType: secret
          objectAlias: POSTGRES_PASSWORD
        - |
          objectName: database-url
          objectType: secret
          objectAlias: DATABASE_URL

  # Create Kubernetes secret from Key Vault secrets
  secretObjects:
  - secretName: postgres-secrets
    type: Opaque
    data:
    - objectName: POSTGRES_DB
      key: POSTGRES_DB
    - objectName: POSTGRES_USER
      key: POSTGRES_USER
    - objectName: POSTGRES_PASSWORD
      key: POSTGRES_PASSWORD
    - objectName: DATABASE_URL
      key: DATABASE_URL

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: credit-card-processor-sa
  namespace: credit-card-processor
  annotations:
    # Workload identity annotation - replace with actual client ID
    azure.workload.identity/client-id: "${AZURE_WORKLOAD_IDENTITY_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"
  labels:
    azure.workload.identity/use: "true"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: credit-card-processor
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: credit-card-processor
subjects:
- kind: ServiceAccount
  name: credit-card-processor-sa
  namespace: credit-card-processor
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
